version: '3'
services:
    mongodb:
        image: mongo:latest@sha256:3a09cd85fb4e76f1d5832f9ea1d4e7481f76e807389b7d8ea6ac4d4ba96f83e5
        environment:
            - MONGO_DATA_DIR=/data/mongodb
            - MONGO_LOG_DIR=/dev/null
            - MONGODB_DBNAME=opal
        command: mongod --smallfiles --logpath=/dev/null # --quiet
        ports:
            - 27017:27017
        volumes:
            - /mnt/db/mongodata:/data/mongodb

    mongodb-initialize:
        image: opalservices/opal-mongodb-initialize:latest@sha256:af1f92b5d59bc21db982b68cb3d7e1acb43934e7659fe1b5756326263d7fb458
        depends_on:
            - mongodb
        links:
            - mongodb

    cache:
        image: opalservices/opal-cache:latest@sha256:327dcfdc695895be0f2481d1bbd45ef18cc4110892070a61b157d53f46f78fdf
        depends_on:
            - mongodb-initialize
        links:
            - mongodb
        volumes:
            - ./opal.cache.config.js:/usr/app/config/opal.cache.config.js

    algoservice:
        image: opalservices/opal-algoservice:latest@sha256:ef796a2b562b409fc1419829372e3fddb61045e6a0011e462364d84bf7f312c1
        depends_on:
            - mongodb-initialize
        links:
            - mongodb
        volumes:
            - ./opal.algoservice.config.js:/usr/app/config/opal.algoservice.config.js
            - /mnt/db/algoservicedata:/usr/app/data
        command: sh -c './src/wait-for.sh mongodb:27017 -- npm start'

    interface:
        image: opalservices/opal-interface:latest@sha256:74f4cb974d75bbd0fce6953da161b2f948e313e180e7a6141b5589b8b8ca0ec3
        depends_on:
            - mongodb-initialize
            - cache
            - algoservice
        links:
            - mongodb
            - cache
            - algoservice
        ports:
            - 80:80
        volumes:
            - ./opal.interface.config.js:/usr/app/config/opal.interface.config.js
