version: '3'
services:
    timescaledb:
        image: timescale/timescaledb:timescaledb:0.9.2-pg9.6
        volumes:
            - /mnt/db/pgdata:/var/lib/postgresql/data

    timescaledb-initialize:
        build:
            context: ..
            dockerfile: ./timescaledb/Dockerfile
        depends_on:
            - timescaledb
        links:
            - timescaledb

    aggandprivacy:
        image: opalservices/opal-privacy:latest@sha256:56d530cd995d3f23934c62a3d3c8a542199c2859dcf3e9934ee66029cc43b6c7
        depends_on:
            - algoservice
        command: sh -c 'npm start'
        volumes:
            - ./opal.privacy.config.js:/usr/app/config/opal.privacy.config.js

    compute:
        image: opalservices/opal-compute:latest@sha256:40ae08155de7b7728101705b0f4a6d012e64ee9ef2e7c7ae47ceb9cde0f89be3
        command: sh -c 'sudo apparmor_init && sleep 5 && sudo npm start'
        privileged: true
        security_opt:
            - apparmor:unconfined
        volumes:
            - ./opal.compute.config.js:/home/opal/app/config/opal.compute.config.js

    scheduler:
        image: opalservices/opal-scheduler:latest@sha256:5c3f516913fa73d6915c093763e7ab9f25073711bbbb37dd1d41a4d9f17c83c6
        depends_on:
            - compute
        links:
            - compute
        volumes:
            - ./opal.scheduler.config.js:/usr/app/config/opal.scheduler.config.js
