version: '3'
services:
    timescaledb:
        image: timescale/timescaledb:latest
        volumes:
            - /mnt/db/pgdata:/var/lib/postgresql/data

    timescaledb-initialize:
        build:
            context: ..
            dockerfile: ./timescaledb/Dockerfile
        depends_on:
            - timescaledb
        links:
            - timescaledb

    aggandprivacy:
        image: opalservices/opal-privacy
        depends_on:
            - algoservice
        command: sh -c 'npm start'
        volumes:
            - ./opal.privacy.config.js:/usr/app/config/opal.privacy.config.js

    compute:
        image: opalservices/opal-compute:latest
        command: sh -c 'sudo apparmor_init && sleep 5 && sudo npm start'
        privileged: true
        security_opt:
            - apparmor:unconfined
        volumes:
            - ./opal.compute.config.js:/home/opal/app/config/opal.compute.config.js

    scheduler:
        image: opalservices/opal-scheduler
        depends_on:
            - compute
        links:
            - compute
        volumes:
            - ./opal.scheduler.config.js:/usr/app/config/opal.scheduler.config.js
