version: '3'
services:
    timescaledb:
        image: timescale/timescaledb:latest
        ports:
            - "5432:5432"
        volumes:
            - /mnt/db/pgdata:/var/lib/postgresql/data

    timescaledb-initialize:
        build:
            context: ..
            dockerfile: ./timescaledb/Dockerfile
        depends_on:
            - timescaledb
        links:
            - timescaledb

    aggandprivacy:
        image: opalservices/opal-privacy
        ports:
            - "9001:80"
        command: sh -c 'npm start'
        volumes:
            - ./opal.privacy.config.js:/usr/app/config/opal.privacy.config.js

    compute:
        image: opalservices/opal-compute:latest
        depends_on:
            - aggandprivacy
            - timescaledb-initialize
        links:
            - aggandprivacy
            - timescaledb
        command: sh -c 'sudo apparmor_init && sudo npm start'
        privileged: true
        security_opt:
            - apparmor:unconfined
        ports:
            - "8001:80"
        volumes:
            - ./opal.compute.config.js:/home/opal/app/config/opal.compute.config.js

    scheduler:
        image: opalservices/opal-scheduler
        depends_on:
            - compute
        links:
            - compute
        ports:
            - "7001:80"
        volumes:
            - ./opal.scheduler.config.js:/usr/app/config/opal.scheduler.config.js
